name: Generate Markdown from JSON

on:
  pull_request:

permissions:
  contents: write

jobs:
  generate-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Generate Markdown
      run: |
        python generate_markdown.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add info-bot-commands.md
        git commit -m "Update info-bot-commands.md"
        git push
